global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Rate Limiter Service
  - job_name: 'rate-limiter-service'
    static_configs:
      - targets: ['rate-limiter-service:8080']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Integrated Service
  - job_name: 'integrated-service'
    static_configs:
      - targets: ['integrated-service:8080']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Redis metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    metrics_path: '/metrics'
    scrape_interval: 15s

  # PostgreSQL metrics
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    metrics_path: '/metrics'
    scrape_interval: 15s

  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node exporter for system metrics (if added)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s
